<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container14s3apa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container14s3apa/appProdProjectContainer.php') {
    touch(__DIR__.'/Container14s3apa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container14s3apa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container14s3apa\appProdProjectContainer([
    'container.build_hash' => '14s3apa',
    'container.build_id' => 'd08662a9',
    'container.build_time' => 1652776265,
], __DIR__.\DIRECTORY_SEPARATOR.'Container14s3apa');
