<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6czd419\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6czd419/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6czd419.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6czd419\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6czd419\appProdProjectContainer([
    'container.build_hash' => '6czd419',
    'container.build_id' => '0cf14ac5',
    'container.build_time' => 1651145073,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6czd419');
