<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3zqa76g\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3zqa76g/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3zqa76g.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3zqa76g\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3zqa76g\appProdProjectContainer([
    'container.build_hash' => '3zqa76g',
    'container.build_id' => '983f39fa',
    'container.build_time' => 1652793683,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3zqa76g');
