<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIcwfus3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIcwfus3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIcwfus3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIcwfus3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIcwfus3\appDevDebugProjectContainer([
    'container.build_hash' => 'Icwfus3',
    'container.build_id' => '451f18d5',
    'container.build_time' => 1651145488,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIcwfus3');
