<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2jcegf9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2jcegf9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2jcegf9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2jcegf9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2jcegf9\appDevDebugProjectContainer([
    'container.build_hash' => '2jcegf9',
    'container.build_id' => 'acdcb3cf',
    'container.build_time' => 1652775776,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2jcegf9');
